language: node_js
node_js:
- node
cache: npm
script:
- npm run test
- npm run build:prod -- --env.rootLocation=kindling
# Uncomment this to use a custom domain
# - cp ./CNAME ./dist

deploy:
  provider: pages
  local_dir: "./dist"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master